# Generated code from Antlr4BuildTasks.dotnet-antlr v __Version__
GENERATED = ArithmeticLexer.cs ArithmeticParser.cs
default:
	dotnet restore
	dotnet build
run:
	dotnet run $(RUNARGS)
clean:
	dotnet clean
	rm -rf bin obj
